# Generated by Django 2.2.4 on 2019-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='board.Comment', verbose_name='Post comments'),
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='post_files', to='content.FileContent', verbose_name='Post files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='post_images', to='content.ImageContent', verbose_name='Post images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='board.Tag', verbose_name='Post Tags'),
        ),
    ]
