# Generated by Django 2.2.4 on 2019-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190822_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='member_only',
            field=models.BooleanField(default=False, verbose_name='Content for member only'),
        ),
        migrations.AddField(
            model_name='post',
            name='member_only',
            field=models.BooleanField(default=False, verbose_name='Content for member only'),
        ),
    ]
