SQLALCHEMY_DATABASE_URI: 'mysql://test:test@db.product.com:1234/testdb'
SQLALCHEMY_TRACK_MODIFICATIONS: false
SECRET_KEY: THIS-IS-SECRET
ACCESS_KEY: something-secret
REFRESH_KEY: something-more-secret
