# Generated by Django 2.2.4 on 2019-08-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.placeholder_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.placeholder_models.SharedCharField(max_length=255, unique=True, verbose_name='name')),
                ('status', models.BooleanField(default=True, verbose_name='Room status')),
                ('capacity', models.IntegerField(verbose_name='Room capacity')),
                ('minimum', models.IntegerField(default=1, verbose_name='Room capacity')),
            ],
            options={
                'verbose_name': 'room status',
                'verbose_name_plural': 'room statuses',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss', to=settings.AUTH_USER_MODEL, verbose_name='Boss')),
                ('member', models.ManyToManyField(blank=True, related_name='member', related_query_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.Room', verbose_name='Which room')),
            ],
            options={
                'verbose_name': 'seminar reservation',
                'ordering': ('-start_time', '-end_time'),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('visit_time', models.DateTimeField(verbose_name='Visit time')),
                ('created_time', models.DateTimeField(verbose_name='Reservation submitted time')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'card reservation',
                'ordering': ('-visit_time',),
            },
        ),
    ]
