# Generated by Django 2.2.4 on 2019-08-22 11:35

from django.db import migrations, models
import django.db.models.deletion
import utils.placeholder_models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iptable', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', utils.placeholder_models.SharedCharField(max_length=255, verbose_name='OS type')),
                ('version', utils.placeholder_models.SharedCharField(blank=True, max_length=255, null=True, verbose_name='OS version')),
                ('edition', utils.placeholder_models.SharedCharField(blank=True, max_length=255, null=True, verbose_name='OS edition')),
                ('bit', utils.placeholder_models.SharedCharField(max_length=255, verbose_name='OS bit')),
            ],
            options={
                'verbose_name': 'OS type',
                'ordering': ('major', 'version', 'bit'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.placeholder_models.SharedCharField(max_length=255, unique=True, verbose_name='Stock status')),
            ],
            options={
                'verbose_name': 'stock status',
                'verbose_name_plural': 'stock statuses',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.placeholder_models.SharedCharField(max_length=255, unique=True, verbose_name='Stock type')),
            ],
            options={
                'verbose_name': 'stock type',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Content UUID Field')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Content created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Content modified date')),
                ('text', models.TextField(blank=True, verbose_name='Content')),
                ('content_type', models.CharField(default='Markdown', max_length=255, verbose_name='Content type')),
                ('stock_id', utils.placeholder_models.SharedCharField(max_length=255, verbose_name='Stock ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('stock_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.StockStatus', verbose_name='Stock status')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.StockType', verbose_name='Stock type')),
            ],
            options={
                'verbose_name': 'stock',
                'ordering': ('stock_id',),
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Stock')),
                ('model_name', utils.placeholder_models.SharedCharField(max_length=255, verbose_name='Computer model name')),
                ('ip_addr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iptable.IPAddress', verbose_name='Allocated IP Address')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.OSType', verbose_name='Installed OS Type')),
            ],
            options={
                'verbose_name': 'computer',
                'ordering': ('stock_id',),
            },
            bases=('inventory.stock',),
        ),
    ]
