# Generated by Django 2.2.4 on 2019-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='member_only',
            field=models.BooleanField(default=False, verbose_name='Content for member only'),
        ),
    ]
