# Generated by Django 2.2.4 on 2019-08-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Content UUID Field')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Content created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Content modified date')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image content',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Content UUID Field')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Content created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Content modified date')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='File caption')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'file content',
                'ordering': ('-created_date',),
            },
        ),
    ]
